In [ ]:
import numpy as np

In [ ]:
# List
a = ([1,2,3])
b = ([[1,2,3], [4,5,6]])

In [ ]:
# Special arrays
zeros = np.zeros((2, 3))
ones = np.ones((3, 3))
identity = np.eye(3)

In [ ]:
# Ranges
c = np.arange(0, 10, 2)
d = np.linspace(0, 1, 5)

In [ ]:
arr = np.arange(5, 55, 5)
reshaped = arr.reshape(5, -1)
reshaped

array([[ 5, 10],
       [15, 20],
       [25, 30],
       [35, 40],
       [45, 50]])

In [ ]:
x = np.array([10, 20, 30, 40, 50])

x[0] # first element

np.int64(10)

In [ ]:
x[-1] # last element

np.int64(50)

In [ ]:
x[1:4] # slicing

array([20, 30, 40])

In [ ]:
m = np.array([[1, 2, 3],
[4, 5, 6],
[7, 8, 9]])

In [ ]:
m[0, 1] # element at row 0, column 1

np.int64(2)

In [ ]:
m[:, 1] # all rows, column 1

array([2, 5, 8])

In [ ]:
sub = m[1:, 1:]
sub

array([[5, 6],
       [8, 9]])

In [ ]:
a = np.array([1, 2, 3])
b = np.array([[10], [20], [30]])

In [ ]:
result = a + b
result

array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [ ]:
np.random.seed(0)
A = np.random.randint(1, 11, size=(4, 3))

In [ ]:
col_means = A.mean(axis=0)

In [ ]:
centered = A - col_means

In [ ]:
A, col_means, centered

(array([[ 6,  1,  4],
        [ 4,  8, 10],
        [ 4,  6,  3],
        [ 5,  8,  7]]),
 array([4.75, 5.75, 6.  ]),
 array([[ 1.25, -4.75, -2.  ],
        [-0.75,  2.25,  4.  ],
        [-0.75,  0.25, -3.  ],
        [ 0.25,  2.25,  1.  ]]))

In [ ]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

In [ ]:
# Element-wise
A * B

array([[ 5, 12],
       [21, 32]])

In [ ]:
# Matrix multiplication
A @ B

array([[19, 22],
       [43, 50]])

In [ ]:
np.dot(A, B)

array([[19, 22],
       [43, 50]])

In [ ]:
A = np.array([[1, 2, 3], [4, 5, 6]])

In [ ]:
# 1. Element-wise square
square = A ** 2

In [ ]:
# 2. A * A^T
product = A @ A.T

In [ ]:
square, product

(array([[ 1,  4,  9],
        [16, 25, 36]]),
 array([[14, 32],
        [32, 77]]))

In [ ]:
M = np.array([[4, 2], [3, 1]])

det = np.linalg.det(M)
inv = np.linalg.inv(M)
eigvals, eigvecs = np.linalg.eig(M)

det, inv, eigvals

(np.float64(-2.0),
 array([[-0.5,  1. ],
        [ 1.5, -2. ]]),
 array([ 5.37228132, -0.37228132]))

In [ ]:
A = np.array([[2, 1], [1, 3]])
b = np.array([5, 6])


x = np.linalg.solve(A, b)
x

array([1.8, 1.4])

In [ ]:
A = np.array([[3, 2], [4, -1]])
b = np.array([16, 9])


solution = np.linalg.solve(A, b)
solution

array([3.09090909, 3.36363636])